import { describe, it, expect } from 'vitest';
import { isLegacyLeetcodeBaseV010, leetcodeBaseYaml } from '../src/notes/BaseFile';

// Exact v0.1.0 YAML string that shipped before GAP-6 was closed. The detector
// probes for its two unique substrings (`file.inFolder("` + `lc-id != null`).
const LEGACY_V010_YAML = [
  '# Auto-generated by the LeetCode plugin on first problem open.',
  '# Feel free to customise views, columns, filters, and sort — the plugin',
  '# will NOT overwrite this file. Delete it to regenerate on next open.',
  'filters:',
  '  and:',
  `    - 'file.inFolder("LeetCode")'`,
  `    - 'file.ext == "md"'`,
  `    - 'lc-id != null'`,
  'views:',
  '  - type: table',
  '    name: Problems',
  '    order:',
  '      - lc-id',
  '      - lc-title',
  '      - lc-difficulty',
  '      - lc-status',
  '      - lc-language',
  '    sort:',
  '      - property: lc-id',
  '        direction: DESC',
  '',
].join('\n');

describe('isLegacyLeetcodeBaseV010 (GAP-6 migration detector)', () => {
  it('returns true for the exact v0.1.0 YAML string', () => {
    expect(isLegacyLeetcodeBaseV010(LEGACY_V010_YAML)).toBe(true);
  });

  it('returns false for the new post-GAP-6 YAML (what leetcodeBaseYaml now emits)', () => {
    expect(isLegacyLeetcodeBaseV010(leetcodeBaseYaml('LeetCode'))).toBe(false);
  });

  it('returns false for the new YAML with a custom folder', () => {
    expect(isLegacyLeetcodeBaseV010(leetcodeBaseYaml('Custom/Problems'))).toBe(false);
  });

  it('returns false for an empty string', () => {
    expect(isLegacyLeetcodeBaseV010('')).toBe(false);
  });

  it('returns false for unrelated arbitrary text', () => {
    expect(isLegacyLeetcodeBaseV010('hello world')).toBe(false);
    expect(isLegacyLeetcodeBaseV010('# user scratchpad')).toBe(false);
  });

  it('returns false for user-customised YAML built on the new schema (has lc-id but not the legacy tokens)', () => {
    const custom = leetcodeBaseYaml('LeetCode') + '\n' + [
      '  - type: table',
      '    name: By difficulty',
      '    filters:',
      '      and:',
      `        - '!note["lc-id"].isEmpty()'`,
      `        - 'note["lc-difficulty"] == "Hard"'`,
      '    order:',
      '      - lc-id',
      '      - lc-title',
    ].join('\n');
    expect(isLegacyLeetcodeBaseV010(custom)).toBe(false);
  });

  it('returns false when only ONE of the two legacy tokens is present (single-token overlap is not enough)', () => {
    // Only file.inFolder — someone's custom view that happens to use that expression
    // but has moved off `lc-id != null`.
    const onlyFolderToken = [
      'filters:',
      '  and:',
      `    - 'file.inFolder("Notes")'`,
      `    - '!note["lc-id"].isEmpty()'`,
    ].join('\n');
    expect(isLegacyLeetcodeBaseV010(onlyFolderToken)).toBe(false);

    // Only lc-id != null — user modified folder expression but kept property check.
    const onlyNullToken = [
      'filters:',
      '  and:',
      `    - 'lc-id != null'`,
    ].join('\n');
    expect(isLegacyLeetcodeBaseV010(onlyNullToken)).toBe(false);
  });

  it('is defensive against non-string input (returns false without throwing)', () => {
    // TypeScript would catch these at compile time — but the runtime guard is
    // cheap insurance against a file-read returning something unexpected.
    expect(isLegacyLeetcodeBaseV010(null as unknown as string)).toBe(false);
    expect(isLegacyLeetcodeBaseV010(undefined as unknown as string)).toBe(false);
    expect(isLegacyLeetcodeBaseV010(42 as unknown as string)).toBe(false);
  });
});
