import { describe, it, expect, vi } from 'vitest';
import { isLegacyLeetcodeBaseV010, leetcodeBaseYaml } from '../src/notes/BaseFile';
import { runLegacyBaseCheck } from '../src/main';

// Exact v0.1.0 YAML string that shipped before GAP-6 was closed. The detector
// probes for its two unique substrings (`file.inFolder("` + `lc-id != null`).
const LEGACY_V010_YAML = [
  '# Auto-generated by the LeetCode plugin on first problem open.',
  '# Feel free to customise views, columns, filters, and sort — the plugin',
  '# will NOT overwrite this file. Delete it to regenerate on next open.',
  'filters:',
  '  and:',
  `    - 'file.inFolder("LeetCode")'`,
  `    - 'file.ext == "md"'`,
  `    - 'lc-id != null'`,
  'views:',
  '  - type: table',
  '    name: Problems',
  '    order:',
  '      - lc-id',
  '      - lc-title',
  '      - lc-difficulty',
  '      - lc-status',
  '      - lc-language',
  '    sort:',
  '      - property: lc-id',
  '        direction: DESC',
  '',
].join('\n');

describe('isLegacyLeetcodeBaseV010 (GAP-6 migration detector)', () => {
  it('returns true for the exact v0.1.0 YAML string', () => {
    expect(isLegacyLeetcodeBaseV010(LEGACY_V010_YAML)).toBe(true);
  });

  it('returns false for the new post-GAP-6 YAML (what leetcodeBaseYaml now emits)', () => {
    expect(isLegacyLeetcodeBaseV010(leetcodeBaseYaml('LeetCode'))).toBe(false);
  });

  it('returns false for the new YAML with a custom folder', () => {
    expect(isLegacyLeetcodeBaseV010(leetcodeBaseYaml('Custom/Problems'))).toBe(false);
  });

  it('returns false for an empty string', () => {
    expect(isLegacyLeetcodeBaseV010('')).toBe(false);
  });

  it('returns false for unrelated arbitrary text', () => {
    expect(isLegacyLeetcodeBaseV010('hello world')).toBe(false);
    expect(isLegacyLeetcodeBaseV010('# user scratchpad')).toBe(false);
  });

  it('returns false for user-customised YAML built on the new schema (has lc-id but not the legacy tokens)', () => {
    const custom = leetcodeBaseYaml('LeetCode') + '\n' + [
      '  - type: table',
      '    name: By difficulty',
      '    filters:',
      '      and:',
      `        - '!note["lc-id"].isEmpty()'`,
      `        - 'note["lc-difficulty"] == "Hard"'`,
      '    order:',
      '      - lc-id',
      '      - lc-title',
    ].join('\n');
    expect(isLegacyLeetcodeBaseV010(custom)).toBe(false);
  });

  it('returns false when only ONE of the two legacy tokens is present (single-token overlap is not enough)', () => {
    // Only file.inFolder — someone's custom view that happens to use that expression
    // but has moved off `lc-id != null`.
    const onlyFolderToken = [
      'filters:',
      '  and:',
      `    - 'file.inFolder("Notes")'`,
      `    - '!note["lc-id"].isEmpty()'`,
    ].join('\n');
    expect(isLegacyLeetcodeBaseV010(onlyFolderToken)).toBe(false);

    // Only lc-id != null — user modified folder expression but kept property check.
    const onlyNullToken = [
      'filters:',
      '  and:',
      `    - 'lc-id != null'`,
    ].join('\n');
    expect(isLegacyLeetcodeBaseV010(onlyNullToken)).toBe(false);
  });

  it('is defensive against non-string input (returns false without throwing)', () => {
    // TypeScript would catch these at compile time — but the runtime guard is
    // cheap insurance against a file-read returning something unexpected.
    expect(isLegacyLeetcodeBaseV010(null as unknown as string)).toBe(false);
    expect(isLegacyLeetcodeBaseV010(undefined as unknown as string)).toBe(false);
    expect(isLegacyLeetcodeBaseV010(42 as unknown as string)).toBe(false);
  });
});

function makeSettingsStub(initial: { flagShown?: boolean; folder?: string } = {}) {
  let flag = initial.flagShown === true;
  return {
    hasShownLegacyBaseNotice: () => flag,
    markLegacyBaseNoticeShown: vi.fn(async () => { flag = true; }),
    getProblemsFolder: () => initial.folder ?? 'LeetCode',
    /** Test-only: peek at the flag's current value. */
    _peekFlag: () => flag,
  };
}

describe('runLegacyBaseCheck (GAP-6 one-time Notice gate)', () => {
  it('fires Notice AND marks the flag when all three conditions are met (v0.1.0 contents, file exists, flag unset)', async () => {
    const settings = makeSettingsStub({ flagShown: false, folder: 'LeetCode' });
    const readBaseFile = vi.fn(async (p: string) => {
      expect(p).toBe('LeetCode/LeetCode.base');
      return LEGACY_V010_YAML;
    });
    const showNotice = vi.fn();
    await runLegacyBaseCheck({ settings, readBaseFile, showNotice });
    expect(showNotice).toHaveBeenCalledTimes(1);
    expect(showNotice).toHaveBeenCalledWith(
      'LeetCode.base may need to be regenerated. Delete it to get the updated view.',
      8000,
    );
    expect(settings.markLegacyBaseNoticeShown).toHaveBeenCalledTimes(1);
    expect(settings._peekFlag()).toBe(true);
  });

  it('is idempotent: a second invocation after the flag is set does NOT fire a Notice', async () => {
    const settings = makeSettingsStub({ flagShown: false, folder: 'LeetCode' });
    const readBaseFile = vi.fn(async () => LEGACY_V010_YAML);
    const showNotice = vi.fn();
    // First run — fires.
    await runLegacyBaseCheck({ settings, readBaseFile, showNotice });
    expect(showNotice).toHaveBeenCalledTimes(1);
    // Second run — short-circuits because flag is now true.
    await runLegacyBaseCheck({ settings, readBaseFile, showNotice });
    expect(showNotice).toHaveBeenCalledTimes(1); // still 1, not 2
    expect(settings.markLegacyBaseNoticeShown).toHaveBeenCalledTimes(1);
  });

  it('does not fire when the flag is ALREADY set (user has seen the Notice previously)', async () => {
    const settings = makeSettingsStub({ flagShown: true, folder: 'LeetCode' });
    const readBaseFile = vi.fn(async () => LEGACY_V010_YAML);
    const showNotice = vi.fn();
    await runLegacyBaseCheck({ settings, readBaseFile, showNotice });
    expect(showNotice).not.toHaveBeenCalled();
    expect(settings.markLegacyBaseNoticeShown).not.toHaveBeenCalled();
    // Read-base should NOT even be attempted if the flag short-circuits first.
    expect(readBaseFile).not.toHaveBeenCalled();
  });

  it('does not fire when the .base file does not exist (readBaseFile returns null)', async () => {
    const settings = makeSettingsStub({ flagShown: false, folder: 'LeetCode' });
    const readBaseFile = vi.fn(async () => null);
    const showNotice = vi.fn();
    await runLegacyBaseCheck({ settings, readBaseFile, showNotice });
    expect(showNotice).not.toHaveBeenCalled();
    expect(settings.markLegacyBaseNoticeShown).not.toHaveBeenCalled();
  });

  it('does not fire when .base exists but contents match the NEW schema (already-migrated user)', async () => {
    const settings = makeSettingsStub({ flagShown: false, folder: 'LeetCode' });
    const readBaseFile = vi.fn(async () => leetcodeBaseYaml('LeetCode'));
    const showNotice = vi.fn();
    await runLegacyBaseCheck({ settings, readBaseFile, showNotice });
    expect(showNotice).not.toHaveBeenCalled();
    expect(settings.markLegacyBaseNoticeShown).not.toHaveBeenCalled();
  });

  it('honours custom problemsFolder — reads from the configured path', async () => {
    const settings = makeSettingsStub({ flagShown: false, folder: 'Custom/Problems/' });
    const readBaseFile = vi.fn(async () => LEGACY_V010_YAML);
    const showNotice = vi.fn();
    await runLegacyBaseCheck({ settings, readBaseFile, showNotice });
    // Trailing slash stripped before path composition (matches ensureLeetcodeBase behaviour).
    expect(readBaseFile).toHaveBeenCalledWith('Custom/Problems/LeetCode.base');
    expect(showNotice).toHaveBeenCalledTimes(1);
  });
});
