// src/notes/BaseFile.ts
// Lazy LeetCode.base writer. Ships ONCE on the first Phase-2 problem open
// (D-18) and never again — users may customise the YAML.
//
// Rules (D-17, D-18, D-22):
//   - Only `vault.create()`; the mutating sibling API is forbidden on
//     problem-note territory (grep-gated via scripts/grep-no-vault-modify.sh).
//   - If the file exists (user opened and kept it, or added custom views):
//     no-op.
//   - If the user deletes it deliberately: the plugin does NOT auto-recreate.
//     (Same preservation posture as Phase 4's technique notes.)
//   - Folder auto-create: if the problems folder itself doesn't exist yet,
//     `vault.create` would throw ENOENT-equivalent. Create the folder first
//     via `vault.createFolder` (Obsidian 1.4.0+ — covered by D-19's 1.10.0
//     minAppVersion bump).
//
// Folder canonicalisation uses the same `.replace(/[\\/]+$/, '')` trailing-
// slash strip SettingsStore.sanitizeFolder uses, so both modules agree on
// the canonical form (Pattern Map: `src/notes/BaseFile.ts` folder-strip).

import type { App } from 'obsidian';

/**
 * Build the YAML content for the `LeetCode.base` file.
 *
 * Exported separately so tests can assert on the content without running
 * `ensureLeetcodeBase` (which requires a mocked Vault).
 *
 * The view declares:
 *   - `filters`: only `.md` files inside the problems folder with an `lc-id` key
 *   - `views[0]`: a table view with five columns (lc-id, lc-title, lc-difficulty,
 *     lc-status, lc-language) sorted by `lc-id` DESC (D-17 — most recently added
 *     problem first). Sort field is MEDIUM-confidence per Pitfall 8; shipped
 *     as-is — Obsidian either honors it or ignores it (no crash either way).
 */
export function leetcodeBaseYaml(folder: string): string {
  const trimmed = folder.replace(/[\\/]+$/, '');
  return [
    '# Auto-generated by the LeetCode plugin on first problem open.',
    '# Feel free to customise views, columns, filters, and sort — the plugin',
    '# will NOT overwrite this file. Delete it to regenerate on next open.',
    'filters:',
    '  and:',
    `    - 'file.inFolder("${trimmed}")'`,
    `    - 'file.ext == "md"'`,
    `    - 'lc-id != null'`,
    'views:',
    '  - type: table',
    '    name: Problems',
    '    order:',
    '      - lc-id',
    '      - lc-title',
    '      - lc-difficulty',
    '      - lc-status',
    '      - lc-language',
    '    sort:',
    '      - property: lc-id',
    '        direction: DESC',
    '',
  ].join('\n');
}

/**
 * Create `{folder}/LeetCode.base` if-and-only-if it does not already exist.
 *
 * - Returns silently on both paths (created / already-present).
 * - Any unexpected error (vault.create throws) propagates to the caller; the
 *   orchestrator (NoteWriter) invokes this in a non-critical path and does
 *   NOT await-throw into user-facing state. Callers typically wrap in try/catch
 *   when the write is purely opportunistic.
 */
export async function ensureLeetcodeBase(app: App, folder: string): Promise<void> {
  const trimmed = folder.replace(/[\\/]+$/, '');
  const path = `${trimmed}/LeetCode.base`;

  // D-18: never overwrite. Check existence first.
  const existing = app.vault.getAbstractFileByPath(path);
  if (existing) return;

  // Ensure the folder exists — `vault.create` is a leaf operation and won't
  // auto-create intermediate folders.
  const folderExists = app.vault.getAbstractFileByPath(trimmed);
  if (!folderExists) {
    await app.vault.createFolder(trimmed);
  }

  await app.vault.create(path, leetcodeBaseYaml(trimmed));
}
